const { default: mongoose } = require("mongoose");

const RoomSchema = new mongoose.Schema({
    authorId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    title:{
        type:String,
        required:true
    },
    slug:{
        type:String,
        required:true,
        unique : true
    },
    roomNumber:{
        type:Number,
        default:null,
        unique:true
    },
    roomStatus:{
        type:String,
        enum:['available','booked','calcel'],
        default:'available'
    },
    mediaType:{
        type:String,
        enum:['image','video'],
        required:true
    },
    media:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    price:{
        type:Number,
        required:true
    },
    discount:{
        type:Number,
        default:0
    },
    finalPrice:{
        type:Number
    },
    bookingDate:{
        type:Date,
        default:null
    },
    bookingCancelDate:{
        type:Date,
        default:null
    }
},{timestamps:true})
module.exports=mongoose.model('Room',RoomSchema)